env:
  node: true
  es2021: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  semi: 0
  no-tabs: 0
  indent: 0
  import/no-extraneous-dependencies: 0
  comma-dangle: 0
  implicit-arrow-linebreak: 0
  object-curly-newline: 0 